from pydoc import describe

import asyncio 
import datetime as dt
import discord
from discord.ext import commands, tasks

#client = discord.Client()

bot = commands.Bot(command_prefix= '!', help_command=None)
bot.remove_command('help')

# @client.event
# async def on_ready():
#    print('We have logged in as {0.user}'.format(client))
#     global botON
#     botON = True


# @client.event
# async def on_message(message):
#     global botON

#     # making sure bot does not respond to itself
#     if message.author == client.user:
#             return

#     if (botON):
#         if message.content.startswith('!hi'):
#             await message.channel.send('hello!')
        
#         if message.content.startswith('!leave'):
#             await message.channel.send('I am leaving!')
#             await client.change_presence(status=discord.Status.invisible)
             
#             botON = False

#     if not(botON):
#         if(message.content.startswith('!join')):
#             await message.channel.send('I am back!')
#             await client.change_presence(status=discord.Status.online)
#             botON = True

#Commands

# sends weekly reminders of episodes that have been newly released per week
@bot.event 
async def showReminder():
    channel = bot.get_channel()
    await channel.send("show 1 - ep: blah blah")
    await channel.send("show 2 - ep: blah blah blah")
    
@showReminder.before_loop
async def before_showReminder():
    for _ in range(60*60*168): # loop per week
        if dt.datetime.now().hour == 10+12: # 24 hour format 
            print("NOTIFICATION - Here are the newly posted episodes for the week!")
            return
        await asyncio.sleep(1) # allows for a moment break before looping once more

# presents list of animes generated by database
@bot.command()
async def createList(context):
    embed = discord.Embed(
        title = '**Generated List of Anime**',
        description = 'Here is your generated list of animes. Use any of the following commands:',
        color = discord.Color.blue()
        # references to database here ?
    )
    embed.add_field(name = 'Commands: ', value= ' `helpMenu`, `showList`, `topAnime`, `recommend`')
    await context.send(embed=embed)

@bot.command()
async def help(context):
    #await context.send("help command - this is a test")
    embed = discord.Embed(
        title = '**Help Menu**',
        description = 'Use any of the following commands:',
        color = discord.Color.blue()
    )
    embed.add_field(name='Commands:',value=' `createList`, `showList`, `topAnime`, `recommend`, `.......`')
    embed.add_field(name='Settings:',value='`.......`', inline = False)
    await context.send(embed=embed)


    
bot.run('OTQyMjgwNzE5NjU1Mzk1MzY5.YgiNTg.e1knou32SWUBoL7iY4p6PcKHETQ')